# Generated by Django 2.1 on 2019-01-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='b_category',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='b_tag',
        ),
    ]
